name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04 - Using Actions/react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm ci
            - name: Run Unit Tests
              run: npm run test

        # 0. checar o código no repositório
        # 1. instalar dependências
        # 2. executar testes de automação