name: 09 - Organization, Repository, and Environment Variables

on:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "I am a workflow env var"
  OVERWRITTEN: "I will be overwritten"
  UNDEFINED_VAR_WITH_DEFAULT: "${{ vars.UNDEFINED_VAR || 'default value' }}"

jobs:
  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: |
          echo "Repo var: $REPOSITORY_VAR"
          echo "Org var: $ORG_VAR"                         # [Requires Organizations]
          echo "Org overwritten var: $OVERWRITTEN_VAR"     # [Requires Organizations]

  echo-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print Prod Variables
        run: |
          echo "Repo var: $REPOSITORY_VAR"
          echo "Org var: $ORG_VAR"                         # [Requires Organizations]
          echo "Org overwritten var: $OVERWRITTEN_VAR"
          echo "Environment var: $TARGET_VAR"

  echo-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print Undefined Variables
        run: |
          echo "Org var: $UNDEFINED_VAR_WITH_DEFAULT"
